baseURL = 'https://www.c-vlad.com/'
languageCode = 'en-us'
title = 'The Intelligence Layer'
canonifyURLs = true                          # forces absolute URLs
relativeURLs = false                         # optional, avoid relative links

theme = "book"

# [permalinks]
# articles = "/:slug/"   # Generates /article-name/ instead of /blog/article-name/

[params]
  project = false
  BookTheme = "light"
  BookToC = true
  BookSection = "*"
 # BookLogo = "/images/AudienceIntelligence.png"
  BookLogo = "/images/TheIntelligenceLayer.png
[markup]
  [markup.goldmark.renderer]
    unsafe = true