baseURL = 'https://www.c-vlad.com/blog/'
languageCode = 'en-us'
title = 'C Vlad'

theme = "book"

[params]
  BookTheme = "light"
  BookToC = true
  BookSection = "*"
  #BookLogo = "/images/logo.png"

[markup]
  [markup.goldmark.renderer]
    unsafe = true